on:
  pull_request:
  push:
    branches:
      - "main"
      - "[0-9].*"

name: Code Coverage

jobs:
  code-coverage:
    name: Code Coverage

    strategy:
      matrix:
        php-version:
          - '8.1'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: intl
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: |
          composer update --no-interaction --no-progress --optimize-autoloader

      - name: Collect code coverage with PHPUnit
        run: |
          vendor/bin/phpunit --coverage-clover=.build/logs/clover.xml

      - name: Send code coverage report to codecov.io
        run: |
          bash <(curl -s https://codecov.io/bash)
